import type { Project, ProjectStatus } from '../types';

export const projectStatusLabels: Record<ProjectStatus, string> = {
  completed: 'Completed',
  'in-progress': 'In Progress',
  planned: 'Planned',
};

/** Display order of the status groups, where projects are grouped by status. */
export const projectStatusOrder: ProjectStatus[] = ['completed', 'in-progress', 'planned'];

/** Every project, in the order the projects page shows them. */
export const projects: Project[] = [
  {
    slug: 'nba-rookie-predictor',
    title: 'NBA Rookie Longevity Predictor',
    tagline: 'Predicting whether an NBA rookie lasts five seasons',
    description:
      "Sports-analytics app that predicts whether an NBA rookie's career will last 5+ years from rookie-season stats, pitting a tuned Logistic Regression against a Decision Tree (74.7% vs 75.4% ROC-AUC).",
    techStack: ['Python', 'scikit-learn', 'Streamlit', 'pandas'],
    status: 'completed',
    memberSlugs: ['kevin', 'fiko', 'david'],
    embedUrl: 'https://predicting-nba-rookie-career-longev.vercel.app/',
    liveUrl: 'https://predicting-nba-rookie-career-longev.vercel.app/',
    repoUrl: 'https://github.com/gretil3/NBA-Rookie-Predictor',
  },
  {
    slug: 'bone-fracture-detection',
    title: 'Bone Fracture Detection',
    tagline: 'Spotting fractures in X-ray images',
    description:
      'Computer vision pipeline for detecting bone fractures in X-ray images using Sobel, Canny, and Watershed segmentation combined with a Random Forest classifier.',
    techStack: ['Python', 'OpenCV', 'scikit-learn'],
    status: 'completed',
    memberSlugs: ['fiko', 'gerald', 'david'],
    embedUrl: 'https://bone-fracture-detection4.streamlit.app/?embed=true',
    liveUrl: 'https://bone-fracture-detection4.streamlit.app/',
    repoUrl: 'https://github.com/gretil3/Bone-Fracture-Detection-Using-OpenCV',
  },
  {
    slug: 'sentiment-market-analysis',
    title: 'Sentiment-Driven Market Analysis',
    tagline: 'Reading market sentiment from financial tweets',
    description:
      'NLP project comparing five models (TF-IDF+LR, TF-IDF+LinearSVC, DistilBERT, FinBERT, and a hybrid) for financial tweet sentiment classification. Fine-tuned DistilBERT achieved the best Macro F1 of 0.848.',
    techStack: ['Python', 'scikit-learn', 'DistilBERT', 'FinBERT', 'Streamlit'],
    status: 'completed',
    memberSlugs: ['gerald', 'david'],
    embedUrl: 'https://twitter-sentiment-nlp-tfidf.streamlit.app/?embed=true',
    liveUrl: 'https://twitter-sentiment-nlp-tfidf.streamlit.app/',
    repoUrl: 'https://github.com/gretil3/Sentiment-Market-Analysis-NLP',
  },
  {
    slug: 'fotoin',
    title: 'FotoIn',
    tagline: 'AI product photos for small online sellers',
    description:
      'Hybrid AI product-photography service for Indonesian UMKM sellers: snap a product with your phone, pick a category, and get photos sized for Shopee, Tokopedia and TikTok Shop, generated by AI, then checked by a person before delivery.',
    disclaimer:
      "Work in progress: the order flow runs end to end, but on a stand-in image generator and mock payments, so there's no public demo yet.",
    techStack: ['Node.js', 'Express', 'React', 'Vite', 'sharp'],
    status: 'in-progress',
    memberSlugs: ['fiko', 'david'],
    repoUrl: 'https://github.com/gretil3/fotoin',
  },
  {
    slug: 'ai-corti',
    title: 'AI.Corti',
    tagline: 'Estimating stress from a wrist sensor',
    description:
      "Research prototype that estimates stress from a wrist sensor's pulse (BVP) and skin-response (EDA) signals, using a CNN + BiLSTM model trained on the WESAD dataset.",
    disclaimer:
      'Work in progress: a research prototype, not a medical tool, and the model is still below its 80% F1 target.',
    techStack: ['Python', 'TensorFlow', 'Streamlit', 'ESP32'],
    status: 'in-progress',
    memberSlugs: ['fiko', 'david', 'gerald', 'kevin'],
    embedUrl: 'https://ai-corti.streamlit.app/?embed=true',
    liveUrl: 'https://ai-corti.streamlit.app/',
    repoUrl: 'https://github.com/geraldadli/ai_corti',
  },
  {
    slug: 'superhoop',
    title: 'Superhoop',
    tagline: 'A projector-and-Arduino basketball arcade',
    description:
      'Embedded-systems take on the Timezone basketball arcade: a projector shows the game, players shoot a small ball at a mini hoop, and an Arduino motion sensor reports each basket.',
    disclaimer:
      'Work in progress: baskets are simulated with the keyboard or a click for now; wiring in the Arduino sensor is next.',
    techStack: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'Arduino'],
    status: 'in-progress',
    memberSlugs: ['fiko', 'david', 'gerald', 'kevin'],
    embedUrl: 'https://superhoop-381x.vercel.app/',
    liveUrl: 'https://superhoop-381x.vercel.app/',
    repoUrl: 'https://github.com/gretil3/superhoop',
  },
  {
    slug: 'civiceye',
    title: 'CivicEye',
    tagline: 'Civic issue reporting with community-funded fixes',
    description:
      'Civic infrastructure reporting platform with real-time issue dispatching via Firebase and the Google Maps API, plus a crowdfunding module for community-funded fixes. Won Best Commercial Potential at Computer Science Festival 2026.',
    techStack: ['React', 'TypeScript', 'Vite', 'Firebase', 'Google Maps API'],
    status: 'completed',
    featured: true,
    memberSlugs: [],
    embedUrl: 'https://civic-eye-azure.vercel.app/',
    liveUrl: 'https://civic-eye-azure.vercel.app/',
    repoUrl: 'https://github.com/gretil3/CivicEye-Updated',
  },
  {
    slug: 'kratt',
    title: 'Kratt',
    tagline: 'Scoring bot activity in YouTube comments',
    description:
      "A media-literacy tool, built by the four of us for UNESCO Youth Hackathon 2026, that scores how much of a YouTube video's comments are bot activity, and shows its reasoning, not just a number.",
    techStack: ['Python', 'FastAPI', 'BERT', 'React Native', 'Expo', 'Docker'],
    status: 'completed',
    featured: true,
    memberSlugs: ['david', 'kevin', 'gerald', 'fiko'],
    embedUrl: 'https://kratt-5433f.web.app/',
    liveUrl: 'https://kratt-5433f.web.app/',
    repoUrl: 'https://github.com/gretil3/kratt',
  },
  {
    slug: 'owi',
    title: 'OWI — Online Web Investigator',
    tagline: 'Flagging coordinated buzzer campaigns',
    description:
      'A buzzer-classification tool for social media comment sections: paste a link from YouTube, X, TikTok, or Instagram, and OWI studies the comments to flag coordinated, paid-looking amplification versus organic opinion.',
    disclaimer:
      'Work in progress: data scraping across platforms is the current sticking point, so features and results will keep changing.',
    techStack: ['TypeScript', 'React', 'Vite', 'Tailwind CSS', 'Framer Motion', 'Express'],
    status: 'in-progress',
    featured: true,
    memberSlugs: [],
    embedUrl: 'https://owi-seven.vercel.app/',
    liveUrl: 'https://owi-seven.vercel.app/',
    repoUrl: 'https://github.com/gretil3/owi',
  },
];

export function getFeaturedProjects(): Project[] {
  return projects.filter((project) => project.featured);
}

export function getProjectsByStatus(status: ProjectStatus): Project[] {
  return projects.filter((project) => project.status === status);
}

export function getProjectsByMember(memberSlug: string): Project[] {
  return projects.filter((project) => project.memberSlugs.includes(memberSlug));
}
